# Generated by Django 5.2.1 on 2025-05-30 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Время приготовления - минимум 1 минута.'), django.core.validators.MaxValueValidator(limit_value=32000, message='Время приготовления - минимум 32000 минут.')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество должно быть больше 0'), django.core.validators.MaxValueValidator(limit_value=32000, message='Количество должно быть меньше 32001')], verbose_name='Количество'),
        ),
    ]
