# Generated by Django 5.2.1 on 2025-05-30 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Время приготовления - минимум 1 минута.'), django.core.validators.MaxValueValidator(limit_value=32000, message='Время приготовления - максимум 32000 минут.')], verbose_name='Время приготовления'),
        ),
    ]
